### ISSUE TITLE
ERC115c.sol and ERC721c.sol _beforeTokenTransfer and _afterTokenTransfer don't override anything

### ISSUE THREAD

**Issue by bedroomlab** [limitbreakinc/creator-token-standards#31] opened 2024-07-12 16:00 UTC
I'm trying to use this in Remix and these functions don't call the super() function and just throw compiler errors

`TypeError: Function has override specified but does not override anything.
  --> .deps/npm/@limitbreak/creator-token-standards/src/erc1155c/ERC1155C.sol:28:24:
   |
28 |     ) internal virtual override {
   |                        ^^^^^^^^
`

**Comment by nathanglb** [comment] 2024-07-15 20:44
This library is built against OpenZeppelin 4+, not 5.  Open Zeppelin changed the underlying implementation between 4.x and 5.x, so you need to point remix at an older version of OpenZeppelin (like 4.9.3).

**Comment by kasper-keunen** [comment] 2024-07-26 21:48
Also running into this problem - i understand that this is OZ related however one would expect if you follow readme instructions that this doesn't happen? Meaning that the instructions should make sure that this happens. 

Because i am getting this error while following the readme instructions (which already set the version of OZ to the correct one). I now think that one of the dependencies somewhere uses the newer OZ and due to that this error occurs - either way its a bad start of trying out this standard by first debugging depenecies for a few hours?

**Comment by kasper-keunen** [comment] 2024-07-26 21:52
So the problem is the Murky is indeed using the newer OZ version and this causes the error!

**Comment by bedroomlab** [comment] 2024-07-27 06:22
Yeah. Can't change the version in Remix. Must resort to other IDEs.

**Comment by nathanglb** [comment] 2024-07-29 20:20
The Remix IDE ignores the correctly set imports that are included in the Creator Token Standards GitHub repository which may be used with Foundry and our npm package which may be used in Hardhat. We recommend using either Foundry or Hardhat.

If you wish to use Remix, this can be resolved by using `@<version>` to explicitly version imports from OpenZeppelin.

**Closed by nathanglb** 2024-07-29 20:20 UTC

**Comment by LB-thomasp** [comment] 2024-07-29 20:29
As @nathanglb mentioned Remix requires adding a version to imports since Remix will pull the latest by default instead of using the package's defined import version.

Here's a quick step by step for doing this in Remix - 

1. Build once to pull initial dependencies
2. Open the Project Find/Replace window in remix
3. Find: @openzeppelin/contracts/
4. Replace with: @openzeppelin/contracts@4.9.3/
5. Clear out the Files to exclude field
6. Build again

![image](https://github.com/user-attachments/assets/41f7d0d1-0459-487a-b1e7-a712f057b31f)

**Comment by MufassirShaw** [comment] 2024-08-01 11:42
I'm facing this issue even after downgrading my OZ version to `4.8.3`. Does anyone have a solution for this? 
Also, should we expect a fix in the next version?

**Comment by LB-thomasp** [comment] 2024-08-01 15:04
@MufassirShaw here is a gist that can be imported into Remix with the necessary version tags applied to compile ERC721C - 

https://gist.github.com/0xth0mas/7fe42d2d990d72bd797d41b1fa8e5bb8
